Vagrantfile
cookbooks/swift/recipes/source.rb
localrc-template

Setting `SWIFT_REPO_BRANCH=2.2.2` in `localrc` allows someone to pin to a specific version.
While this may not be terribly helpful for developing Swift itself, it does let consumers developing applications against Swift work against the version they use in production. (This is our use case.)

Allow using tagged releases of Swift

---

bin/rebuildswift
bin/reinstallswift
bin/remakerings
bin/resetswift

The script was complaining about a missing dir under tmp. The pathing
just appeared to be incorrect. After making the minor change included
in this commit, the script ran successfully.

Fixing rebuildswift

---

cookbooks/swift/recipes/setup.rb

python{2.6, 3.3} and python{2.6, 3.3}-dev were not required; tox.ini was not using either. Removing these packages then made the deadsnakes ubuntu PPA unnecessary.
I found that python2.6-dev seemingly was needed to build the wheels from the cryptography package in swift, but adding the OpenSSL development package (libssl-dev) fixed this.

Clean-up Python-related packages.

---

cookbooks/swift/files/default/etc/swift/proxy-server/proxy-server.conf.d/20_settings.conf
cookbooks/swift/recipes/source.rb
cookbooks/swift/templates/default/etc/swift/proxy-server/default.conf-template.erb

There is no need to pull the encrypter/decrypter middleware anymore from the Gerrit crypto branch as it was merged upstream:
https://review.openstack.org/#/c/194191/
https://github.com/openstack/swift/commit/f3231ff407bd731b054a42e2070be5768103fd18

Remove pulling of unmerged encrypter/decrypter middleware changes from Gerrit

---

cookbooks/swift/recipes/source.rb

These changes are needed in crypto, or else `vagrant up` fails since the recent Swift master->feature/crypto merge.

work around swift-bench pbr requirements

---

cookbooks/swift/files/default/etc/apt/sources.list.d/fkrull-deadsnakes-precise.list
cookbooks/swift/files/default/etc/apt/sources.list.d/fkrull-deadsnakes-trusty.list
cookbooks/swift/recipes/setup.rb

the swift VM runs on trusty, trying to install python3.4 from fkrull-deadsnakes
for precise will result in file clashes. Specifically, libpython3.4-stdlib
3.4.3-2+precise1 and libpython3.4-minimal 3.4.3-1ubuntu1~14.04.3

move fkrull-deadsnakes PPA to trusty

---

Vagrantfile
cookbooks/swift/recipes/source.rb
localrc-template

as experienced in
https://github.com/swiftstack/vagrant-swift-all-in-one/issues/28
virtualbox might not allow symlinks on /vagrant. Work around that by
introducing SOURCE_ROOT to be able to override git clone location.

introduce SOURCE_ROOT to clone git repositories into

---

cookbooks/swift/recipes/setup.rb

Without this, the latest code in feature/crypto can't be built.
It seems to fail when building the wheels for PyECLib; get errors
about needing `liberasurecode.so.1` and a message to install
`liberasurecode-dev`.

Adds liberasurecode-dev to the required packages

---

Vagrantfile
cookbooks/swift/recipes/setup.rb

Hi,
We've just started using this to provision swift hosts for testing a backups tool. We've got it up and running on AWS, using an ubuntu base image and your existing chef cookbooks.
The only cookbook change we had to make was adding the vagrant user if it does not already exist, to support use of community AMIs that were not explicitly produced for use as a vagrant box (such as the official Canonical Ubuntu 14.04 image).
cc @mariantalla

support vagrant AWS provider

---

Vagrantfile

Let's increase the default RAM in the Vagrantfile too, if one is not using a sourced localrc.

Increase default RAM in Vagrantfile

---

cookbooks/swift/recipes/setup.rb

ppa:fkrull/deadsnakes appears to not work any more, at least on
Xenial. The GPG key is something like
"tag:launchpad.net:2008:redacted", which isn't a real GPG key
fingerprint, and you can't add the PPA. There's now one at
ppa:deadsnakes/ppa that works on Xenial, so let's use that instead.

Use new deadsnakes; old deadsnakes is dead

---

bin/vtox

Commit 0421932 got rid of a bunch of setup.py hackery, but it missed
this line, so after running vtox you have this _setup.py file laying
around. It doesn't hurt anything, but it shows up as an untracked file
in `git status`.

vtox: don't create _setup.py

---

cookbooks/swift/recipes/setup.rb

swiftclient and swift are both testing against 3.5 and not 3.4.
I also got rid of Python 2.6 since nothing's testing against that any more.

Install Python 3.5, not 3.4, and not 2.6.

---

bin/vtox

The OpenStack gate is checking py35, so let's do that locally by
default. Otherwise it's too easy to push a change that breaks py35
because you just ran "vtox" and called it good.

Add py35 to vtox's default environments.

---

Vagrantfile
bin/rebuildswift
bin/reinstallswift
bin/remakerings
bin/resetswift

...rather than /tmp/vagrant-chef-#
Now, `resetswift` will still work following a `vagrant reload`
Fixes #58.

Drop chef provisioning inputs into /etc/chef

---

bin/cleanswift
cookbooks/swift/files/default/etc/swift/account-server/default.conf-template
cookbooks/swift/files/default/etc/swift/container-server/default.conf-template
cookbooks/swift/recipes/data.rb
cookbooks/swift/recipes/setup.rb
cookbooks/swift/templates/default/etc/rsyncd.conf.erb
cookbooks/swift/templates/default/etc/swift/object-server/default.conf-template.erb

Previously, we would create one loopback device with some subdirs to represent "drives" and symlink them into place under `/srv/node*`
Now, use N loopback devices. Note that you may want to crank down `LOOPBACK_GB` as it applies to each sparse file and the default may allow you to fill your VM's root disk. (Not immediately -- the files are still sparse -- but PUT enough data and you'll fill up.)
Two side benefits (beyond getting closer to "real" system behavior):
- we can now enable mount_check, and
- we can have per-node-and-service rsync modules.

Use real mount points

---

cookbooks/swift/files/default/etc/ansible/hosts
cookbooks/swift/recipes/losf.rb

Maybe you'd rather have the index server start in a chef recipe ? (if we use the ansible run.yaml, as I did, it does start, but it also run the functests, which we may not want to do automatically in the SAIO case)

Change zuul src_dir and add run.yaml step

---

.functions.sh
cookbooks/swift/recipes/setup.rb

I don't like echo'ing functions directly into .profile
it makes quoting annoying
testing updates requires re-running provision
update to the cod requires some tricky greps
I would prefer we don't really need bash functions, dropping small scripts in `vagrant/bin` makes them more obvious/discoverable and allows them to eventually "grow out" of bash  - but unfortunately bin scripts aren't a good fit when the goal is to manipulate the current bash environment
I'd like to get some feedback on if this is the right way to go

start collecting .function.sh

---

.s3cfg
Vagrantfile
bin/rebuildswift
cookbooks/swift/files/default/etc/haproxy/haproxy.cfg
cookbooks/swift/files/default/etc/swift/container-sync-realms.conf
cookbooks/swift/recipes/configs.rb
cookbooks/swift/recipes/setup.rb
cookbooks/swift/templates/default/etc/ssl/private/saio.conf.erb
cookbooks/swift/templates/default/etc/swift/container-sync-realms.conf.erb
cookbooks/swift/templates/default/etc/swift/dispersion.conf.erb
cookbooks/swift/templates/default/etc/swift/proxy-server/proxy-server.conf.d/20_settings.conf.erb
cookbooks/swift/templates/default/etc/swift/test.conf.erb
cookbooks/swift/templates/default/home/aws/config.erb
cookbooks/swift/templates/default/home/s3cfg.erb
localrc-template

Have haproxy listen on both 443 and 80; client needs to be smart about whether it wants TLS or not.
Uses the PROXY protocol support introduced back in Swift 2.18.0; if you're testing an old version of Swift, you'll need to drop the `send-proxy` in `/etc/haproxy/haproxy.cfg`.
See also: #51

Add TLS support using haproxy

---

cookbooks/swift/recipes/setup.rb

Hello,
Since https://review.opendev.org/#/c/699457/, OS_AUTH_TYPE variable is read and rejected by python-swiftclient.
I suggest to remove it because I don't think is it currently used.
Edouard

Remove OS_AUTH_TYPE env variable

---

Vagrantfile
cookbooks/swift/recipes/configs.rb
cookbooks/swift/recipes/rings.rb
cookbooks/swift/templates/default/etc/swift/account-server/replication.conf-template.erb
cookbooks/swift/templates/default/etc/swift/account-server/server.conf-template.erb
cookbooks/swift/templates/default/etc/swift/account-server/settings.conf.erb
cookbooks/swift/templates/default/etc/swift/container-server/replication.conf-template.erb
cookbooks/swift/templates/default/etc/swift/container-server/server.conf-template.erb
cookbooks/swift/templates/default/etc/swift/container-server/settings.conf.erb
cookbooks/swift/templates/default/etc/swift/node.conf-template.erb
cookbooks/swift/templates/default/etc/swift/object-server/replication.conf-template.erb
cookbooks/swift/templates/default/etc/swift/object-server/server.conf-template.erb
cookbooks/swift/templates/default/etc/swift/object-server/settings.conf.erb
localrc-template

Export `REPLICATION_SERVERS=true` to enable. When enabled:
* [1-4].conf.d will *only* have configs for the data-network servers.
* [5-8].conf.d will have the replication-network servers bound on ports 605x-608x, as well as configs for all background daemons.
Note that some upstream changes are required to get probe tests passing; at the very least,
* account-reaper needs to be willing to look at replication_port to determine whether a device is local
* container-sync needs to do the same
* probe test brain probably needs to include replication servers when starting/stopping halves

Be able to configure replication network

---

bin/autodoc

By using `tox -e docs`, it should work when swift is running under py2, too -- see #100 / #101.

py3-ify autodoc

---

cookbooks/swift/templates/default/etc/pykmip/server.conf.erb

I guess the client uses OS defaults, and those got more secure?
TLS1.2 seems to work fine on bionic, so I'm calling it good.

Fix PyKMIP on focal

---

cookbooks/swift/recipes/source.rb

When pip installing swiftclient test-requirements, pip might fail to
install PyYAML because of an existing installation of the
package. This can be avoided by using the --ignore-installed option.

Use --ignore-installed with pip install of swiftclient

---

cookbooks/swift/recipes/setup.rb

This patch changes the setup recipe to point to the correct location.

The get-pip.py script for py 2.7 moved slightly

---

cookbooks/swift/templates/default/etc/pykmip/server.conf.erb

We were hardcoding TLS ciphers that no longer work (by default?) on jammy.

Fix PyKMIP on jammy

---

cookbooks/swift/recipes/configs.rb

Otherwise, you aren't ready to run probe tests following a reload.
For example, try running
```
vagrant destroy -f ; vagrant up ; vagrant reload ; vagrant ssh -c 'cd swift && pytest -x test/probe'
```
before/after the change; before, you'll see a bunch of
```
SKIPPED (unable to connect to rsync export {replication_ip}::account_{device} (rsync 127.0.0.1::account_sdb1))
```

Enable rsync on jammy

---

cookbooks/swift/recipes/configs.rb
cookbooks/swift/recipes/source.rb

fixes #154
Running vagrant up was failing when there was no existing VM.
The "fix certifi" task in `source.rb` requires the certificate, which is
not created until the "create cert" task in `config.rb` later in the process.
This change ensures that the VM creates successfully by making the
"fix certifi" task in `source.rb` conditional on the certificate existing.
It also restores the "fix certifi" task to config.rb so that it is run both
on provision, and with the `reinstallswift` script.

fix clean deployment

---

.gitignore

This folder is useful for local development and testing e.g. making changes to nv-swift-gizmos.

Add /.scratch folder to .gitignore

---

cookbooks/swift/templates/default/etc/swift/internal-client.conf.erb
cookbooks/swift/templates/default/etc/swift/proxy-server/default.conf-template.erb

This will facilitate `test swift-integrity delete --dry-run` to correctly detect unreaped/expired objects correctly by default.
Testing:
```
cchigbo@cchigbo-mlt vagrant-swift-all-in-one % vagrant destroy
cchigbo@cchigbo-mlt vagrant-swift-all-in-one % vagrant ssh
vagrant@vagrant:~$ cat /etc/swift/internal-client.conf # verified that the line  allow_open_expired = True
vagrant@vagrant:~$ cat /etc/swift/proxy-server/default.conf-template # verified that the line allow_open_expired = true was present
```

Set allow_open_expired = true by default in vsaio

---

cookbooks/swift/files/default/etc/prometheus/statsd_mapping.yaml

We're instrumenting some mw who's labeled metrics won't start with swift_
When testing labeled metrics in a vsaio I don't think that "any metric we don't know" is the right scope for the prom exporter - really only metrics that are trying to use "dots" in the name to mean *labels* should be flagged up to have their fields parsed/annotated
... and hopefully there won't be much more of that going on.  For any NEW metric we're adding to swift (or else where) it should hopefully use the labeled format and tell us what the field names are explicitly!
FWIW the metric in question was showing up in my vsaio prom like this before:
```
unknown_raw_metric_counter{event="handle_request", host="proxy", instance="localhost:9100", job="saio", method="GET", name="s8ka_request", scope="authen", …
```

let new non swift_* labeled metrics through
