NVIDIA/vagrant-swift-all-in-one

cookbooks/swift/files/default/etc/swift/proxy-server/proxy-server.conf.d/20_settings.conf, cookbooks/swift/templates/default/etc/swift/proxy-server/default.conf-template.erb
This change was done in Swift feature/crypto here:
https://review.openstack.org/#/c/244904/
=> Update proxy-server to reflect change from trivial_keymaster->keymaster

Vagrantfile, cookbooks/swift/files/default/etc/swift/container-server/default.conf-template, cookbooks/swift/files/default/etc/swift/proxy-server/proxy-server.conf.d/20_settings.conf, cookbooks/swift/recipes/configs.rb, cookbooks/swift/templates/default/etc/swift/internal-client.conf.erb, cookbooks/swift/templates/default/etc/swift/proxy-server/default.conf-template.erb, localrc-template
it defaults to off, merge this when crypto lands on master
=> optionally enable encryption

.gitignore, Vagrantfile, bin/vtox, cookbooks/swift/files/default/etc/apt/sources.list.d/fkrull-deadsnakes-trusty.list, cookbooks/swift/recipes/configs.rb, cookbooks/swift/recipes/data.rb, cookbooks/swift/recipes/default.rb, cookbooks/swift/recipes/rings.rb, cookbooks/swift/recipes/setup.rb, cookbooks/swift/recipes/source.rb, cookbooks/swift/templates/default/etc/rsyncd.conf.erb, cookbooks/swift/templates/default/etc/swift/base.conf-template.erb, localrc-template
@matthewoliver look xenial!  I know you prefer to saio in the cloud - but technically there's a vagrant rackspace provider - i haven't tried it but it could be right in your wheelhouse!
=> xenial support

Vagrantfile, localrc-template
@timuralp can you check this out?
=> duh, unix needs that other name

cookbooks/swift/files/default/etc/swift/proxy-server/proxy-noauth.conf.d/20_settings.conf, cookbooks/swift/files/default/etc/swift/proxy-server/proxy-server.conf.d/20_settings.conf, cookbooks/swift/templates/default/etc/swift/internal-client.conf.erb, cookbooks/swift/templates/default/etc/swift/proxy-server/default.conf-template.erb
merge this after https://review.openstack.org/#/c/232162 lands
=> add symlink to the pipeline

bin/vtox
The rationale is spelled out in vtox
=> Speed up vtox runs after setup.[py|cfg] updates

Vagrantfile, chef.conf
Add a Chef configuration file to work around the behavior of Chef 15
regarding licence acceptation.
Fixes #82
=> Add a Chef configuration to accept licence

Vagrantfile, cookbooks/swift/recipes/setup.rb, localrc-template
...which means that services will be brought up under py3!
=> Add config option to install swift under py3

cookbooks/swift/recipes/source.rb
... let's not install them by default
=> doc requirements are py3 only

cookbooks/swift/templates/default/etc/swift/proxy-server/default.conf-template.erb, cookbooks/swift/templates/default/etc/swift/proxy-server/proxy-server.conf.d/20_settings.conf.erb
move the development environment more inline what we think people should be running in production
=> Fix pipeline

bin/cleanswift
Should make probe tests a little more robust.
=> Kill orphans after stopping swift

.copyright.config.json, .copyright.templates.json, Vagrantfile, bin/autodoc, bin/cleanswift, bin/kmipkey, bin/memcachedstats, bin/rebuildswift, bin/reec, bin/reinstallswift, bin/remakerings, bin/resetswift, bin/venv, bin/vtox, cookbooks/swift/recipes/ansible.rb, cookbooks/swift/recipes/configs.rb, cookbooks/swift/recipes/data.rb, cookbooks/swift/recipes/default.rb, cookbooks/swift/recipes/pykmip.rb, cookbooks/swift/recipes/rings.rb, cookbooks/swift/recipes/setup.rb, cookbooks/swift/recipes/source.rb, cookbooks/swift/recipes/zipkin.rb, cookbooks/swift/templates/default/etc/rc.local.erb
[NSVISCS-1361]
Auto-added using this command-line:
```
copyright -S -q -c .copyright.config.json -A -t .copyright.templates.json -e '*.md,*.patch,*.conf,*.conf.erb,*-template.erb,*-template,config.erb' *
```
=> Include notices & attributions in each source code file

cookbooks/swift/recipes/setup.rb
=> get-pip url for py2 changed

cookbooks/swift/recipes/setup.rb
=> pip 2.7 install fails

cookbooks/swift/files/default/etc/swift/object-expirer.conf.d/20_settings.conf, cookbooks/swift/templates/default/etc/swift/proxy-server/default.conf-template.erb
change a few configs to be a little bit more like the way we run in prod
=> More like prod

README.parallels, Vagrantfile, localrc-template
NOTE: Parallels section changes were made by Matthew Oliver.
=> Add Parallels support on Apple M1 processor.

Vagrantfile
Just changing the localrc-template is insufficient; make sure unset is interpreted as true.
=> Use py3 by default

cookbooks/swift/recipes/setup.rb, cookbooks/swift/recipes/source.rb
Also clean up a few stale dependencies.
=> Be able to bring up a py2 VSAIO

cookbooks/swift/recipes/setup.rb, cookbooks/swift/templates/default/home/aws/credentials.erb
https://jirasw.nvidia.com/browse/NSVISCS-5311
=> Adding .aws/credentials file

README.libvirt, Vagrantfile, localrc-template
Still need to fix ip address assigning.
=> Libvirt: add libvirt support and documentation

cookbooks/swift/recipes/setup.rb, cookbooks/swift/templates/default/home/rclone/rclone.erb
Automatically install rclone and setup rclone.conf with all the tempauth accounts setup for both swift and s3.
=> Add rclone to Vsaio

cookbooks/swift/templates/default/etc/swift/proxy-server/proxy-server.conf.d/20_settings.conf.erb
Maybe this can we squashed with the backend ratelimit change #125
=> Always configure staticweb
